module.exports = Object.freeze({
    CANVAS_WIDTH: 600 , // Total drawing canvas

    //Document margins
    TOP_MARGIN: 10 ,
    BOTTOM_MARGIN: 0 ,
    LEFT_MARGIN: 20 ,
    RIGHT_MARGIN: 10 ,

    //Line width
    HEADING_LINE_WIDTH : 1.5 ,
    HEADING_LINE_COLOR :'black',
    HEADING_FONT_SIZE:10 ,
    HEADER_WIDTH :600 ,
    DEFAULT_LINE_WIDTH :0.5,

    // Footer details
    FOOTER_FONT_SIZE :6 ,
    FOOTERNOTES_FONT_SIZE :10,
    FOOTER_FIRSTBOUNDARY_YPOSITION :730,
    FOOTER_SECONDBOUNDARY_YPOSITION:700,
    FOOTER_NOTES_YPOSITION:670,
    FOOTERTEXT_YMARGIN : 2 ,
    FOOTERNOTESTEXT_YMARGIN :6,
    FOOTERATTRIBUTES_TEXTMARGIN:125,
    //Drawing canvas dimensions
    CANVAS_STARTINGXPOSITION : 30,
    CANVAS_STARTINGYPOSITION : 60 ,
    CANVAS_WIDTH : 500 ,
    CANVAS_HEIGHT : 600,
    PERCENTAGE_AVAILABLE_WIDTH_FOR_SHELVES :0.85 ,
    LEGEND_BOX_SIZE:4,
    LEGEND_BOX_MARGIN:5,
    DISPLAY_GROUP_DESCRIPTION_STARTPOSITION :250,
    LEGEND_STARTPOSITION :260,
    PRODUCTTYPE_DESCRIPTION_STARTXPOSITION :310,
    PRODUCTTYPE_DESCRIPTION_STARTYPOSITION :12,
    PRODUCTTYPE_BOX_SIZE:10,
    PRODUCTTYPE_WIDTH_BETWEENBOXES:80,
    PRODUCTTYPE_LEGENDTEXT_ALIGNMENTXPOSITION:4,
    PRODUCTTYPE_LEGENDTEXT_ALIGNMENTYPOSITION:2,
    PRODUCTTYPE_LEGENDDESCRIPTION_ALIGNMENTXPOSITION:12,
    PRODUCTTYPE_LEGENDTEXTFONT_SIZE :8,
    PRODUCTTYPE_DESCRIPTIONFONT_SIZE :6,
    PRODUCTTYPE_DESCRIPTION_WIDTH :60,

    STANDARD_SHELF_THICKNESS : 4 ,
    SHELF_COLOR : 'black' ,
    PRODUCT_BORDER_COLOR : 'black',
    SHELF_DIMENSION_DETAILS_WIDTH : 50 ,
    FIXTURE_DIMENSION_DETAILS_WIDTH : 40,
    FIXTURE_DIMENSION_DETAILS_HEIGHT : 40,
    DEFAULT_TEXTFONT_SIZE :6,
    SHELF_FILL_COLOR :'black',
    SHELF_STROKE_COLOR :'black',
    DEFAULT_FONTCOLOR :'black',
    DEFAULT_STROKECOLOR:'black' ,
    LEGEND_NEWPRODUCT_COLOR :'black',
    LEGEND_NOCHANGE_COLOR :'white',
    LEGEND_NEWLOCATION_COLOR :'grey',
    LEGEND_TEXT_FONTSIZE :5 ,
    VERTICALSHELF_LINE_COLOR : 'black',
    DEFAULT_DRAWING_COLOR:'black'
});